/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComercialRouteImport } from './routes/comercial'
import { Route as ConversaoRouteImport } from './routes/conversao'
import { Route as LeadsRouteImport } from './routes/leads'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialRoute = ComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversaoRoute = ConversaoRouteImport.update({
  id: '/conversao',
  path: '/conversao',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comercial': typeof ComercialRoute
  '/conversao': typeof ConversaoRoute
  '/leads': typeof LeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comercial': typeof ComercialRoute
  '/conversao': typeof ConversaoRoute
  '/leads': typeof LeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comercial': typeof ComercialRoute
  '/conversao': typeof ConversaoRoute
  '/leads': typeof LeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/comercial' | '/conversao' | '/leads'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comercial' | '/conversao' | '/leads'
  id: '__root__' | '/' | '/comercial' | '/conversao' | '/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComercialRoute: typeof ComercialRoute
  ConversaoRoute: typeof ConversaoRoute
  LeadsRoute: typeof LeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial': {
      id: '/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof ComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversao': {
      id: '/conversao'
      path: '/conversao'
      fullPath: '/conversao'
      preLoaderRoute: typeof ConversaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComercialRoute: ComercialRoute,
  ConversaoRoute: ConversaoRoute,
  LeadsRoute: LeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
